apiVersion: v1
kind: Service
metadata:
  name: configmapspringbootservice
  labels:
    name: configmap
spec:
  selector:
    app: configmap-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008
  type: LoadBalancer