apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-deployment-new
  labels:
    app: configmap-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: configmap-app
  template:
    metadata:
      labels:
        app: configmap-app
    spec:
      containers:
        - name: configmap-app
          image: configmap-springboot-0.0.1.jar
          ports:
            - containerPort: 8081
      envFrom:
        - configMapRef:
            name: configmapdata