apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: skaffold-spring-boot-config-example
      jib: {}
  local: {}

deploy:
  kubectl:
    manifests:
      - k8s-* #yaml-files are starts with